version: '3.3'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - ./table:/docker-entrypoint-initdb.d


  app:
    depends_on:
      - mysqldb
    build: ./invoicemysql-app
    restart: unless-stopped
    env_file: ./.env
    ports: 
      - 6868:8080
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=3306
    stdin_open: true
    tty: true

volumes: 
  db: